development:
  only:
    - develop
  script:
    - git ftp push --user $SFTP_FYS_USER --passwd $SFTP_FYS_PASS sftp://sftp.fys.cloud:22/dev --insecure
production:
  only:
    - master
  script:
    - git ftp push --user $SFTP_FYS_USER --passwd $SFTP_FYS_PASS sftp://sftp.fys.cloud:22/live --insecure
mockup:
  only:
    - mockup
  script:
    - git ftp push --user $SFTP_FYS_USER --passwd $SFTP_FYS_PASS sftp://sftp.fys.cloud:22/mockup --insecure
